# Colors (Everforest Light)

# Default colors
[colors.primary]
# filip: modified this to hard 
background = '#fffbef'
foreground = '#5c6a72'

# Normal colors
[colors.normal]
black   = '#5c6a72'
red     = '#f85552'
green   = '#8da101'
yellow  = '#dfa000'
blue    = '#3a94c5'
magenta = '#df69ba'
cyan    = '#35a77c'
white   = '#e0dcc7'

# Bright Colors
[colors.bright]
# Changed this   to make autosuggestions legible
# I looked at the palletes on https://github.com/sainnhe/everforest and picked
black   = '#a6b0a0'
red     = '#f85552'
green   = '#8da101'
yellow  = '#dfa000'
blue    = '#3a94c5'
magenta = '#df69ba'
cyan    = '#35a77c'
white   = '#e0dcc7'
